server:
  port: 8081
  servlet:
    context-path: /api

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/callcenter
    username: postgres
    password: ${DB_PASSWORD:123456}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 300000
      connection-timeout: 20000

  config:
    import: optional:file:./.env.yaml

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  type-aliases-package: io.github.nwen.freecallcenterapi.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

freeswitch:
  esl:
    host: 172.16.80.176
    port: 8021
    password: ${FS_PASSWORD:ClueCon}
    timeout: 5000

logging:
  level:
    root: INFO
    io.github.nwen.freecallcenterapi: DEBUG
